#!/usr/bin/env bash

pacmd set-card-profile 0 output:hdmi-stereo-extra1+input:analog-stereo
notify-send "Docked"

# Picom
killall -q picom
while pgrep -x picom >/dev/null; do sleep 1; done
#picom --experimental-backends --backend glx --blur-method dual_kawase --blur-strength 20 &
picom &
 
# wallpaper
# if [ -f ~/.cache/bg ]; then
#   sleep 4; xwallpaper --zoom ~/.cache/bg &
# else
#   cp $(find $(pwd)/Pictures/Wallpapers -type f | sort -R |head -n1) ~/.cache/bg && convert -resize 1920 -blur 30x30 ~/.cache/bg ~/.cache/bg.png && xwallpaper --zoom ~/.cache/bg &
# fi

# bspwm
bspc wm -r

# Polybar
# $HOME/.config/polybar/launch.sh &
