#!/usr/bin/env sh

## common between WM's and DE's
# [ -f ~/.xprofile ] && . ~/.xprofile
#[ -f ~/.xsessionrc ] && . ~/.xsessionrc

## desktop i3
#sxhkd -c "$HOME"/.config/sxhkd/bspwm "$XDG_CONFIG_HOME"/sxhkd/sxhkdrc &
#"$HOME"/.config/polybar/launch.sh &
#exec i3

# BSPWM
#sxhkd -c $HOME/.config/sxhkd/bspwm $XDG_CONFIG_HOME/sxhkd/sxhkdrc &
#$HOME/.config/polybar/launch.sh &
#picom -b --experimental-backends --backend glx --blur-method dual_kawase --blur-strength 10 &
#exec bspwm

## DWM
~/.scripts/touchpad-enable.sh &
exec dwm
