#!/usr/bin/env bash

pacmd set-card-profile 0 output:analog-stereo+input:analog-stereo
notify-send "Laptop"
killall picom && picom --experimental-backends --backend glx --blur-method dual_kawase --blur-strength 20
