#!/usr/bin/env bash

pacmd set-card-profile 0 output:analog-stereo+input:analog-stereo
notify-send "Laptop"
killall picom; picom --experimental-backends --backend glx --blur-method dual_kawase --blur-strength 20

# wallpaper
if [ -f ~/.cache/bg ]; then
  sleep 4; xwallpaper --zoom ~/.cache/bg &
else
  cp $(find $(pwd)/Pictures/Wallpapers -type f | sort -R |head -n1) ~/.cache/bg && convert -resize 1920 -blur 30x30 ~/.cache/bg ~/.cache/bg.png && xwallpaper --zoom ~/.cache/bg &
fi
