#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP1 -n 0 -d I II III IV V
bspc monitor HDMI2 -d VI VII VIII IX X
bspc wm -O eDP1 HDMI2

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# wallpaper
# if [ -f ~/.cache/bg ]; then
#   xwallpaper --zoom ~/.cache/bg &
# else
#   cp $(find $(pwd)/Pictures/Wallpaper -type f | sort -R |head -n1) ~/.cache/bg && convert -resize 1920 -blur 30x30 ~/.cache/bg ~/.cache/bg.png && xwallpaper --zoom ~/.cache/bg &
# fi &

