#!/usr/bin/env bash

xrandr --output eDP-1-1 --off --output DP-1-1 --off --output HDMI-1-1 --off --output HDMI-1-2 --mode 1920x1080 --pos 0x0 --rotate normal
bspc monitor eDP-1-1 --remove
bspc monitor HDMI-1-2 -d 1 2 3 4 5 6 7 8 9 10
nvidia-settings &
steam &
